### ISSUE TITLE
AntiAntiDebug - Issue

### ISSUE THREAD

**Issue by 0x11DFE** [2365103939/ExtremeDumper#1]
While i was trying to use AntiAntiDebug i get same error on any file.

<img src="https://i.imgur.com/FiPwX4Q.png"></img>

**Comment by wwh1004** [comment]
You can only use AntiAntiDump mode to dump a module, not the whole process. Because in many cases only one assembly is protected, not all assemblies need to use AntiDump mode to dump.

**Comment by wwh1004** [comment]
Right-click on a process, click on the view module, and you can just dump a module.

**Comment by 0x11DFE** [comment]
> Right-click on a process, click on the view module, and you can just dump a module.

Now i did a test with an CLR Hosted app with Anti Dump
<img src="https://i.imgur.com/kNijKEa.png"></img>

**Comment by wwh1004** [comment]
Could you send me your unpackme? And some modules may can't be dumped by using antiantidump mode. You need to use x64dbg + normal mode to dump.

**Comment by 0x11DFE** [comment]
> Could you send me your unpackme? And some modules may can't be dumped by using antiantidump mode. You need to use x64dbg + normal mode to dump.

I know how to dump with x64dbg but isn't this tool made for simple use 😋
Sending you the file to your email, i will avoid to publish publicly.

**Comment by wwh1004** [comment]
I can't fix it. This may be a bug in ClrMD. Ant antiantidump mode not supports #- table stream.

**Comment by 0x11DFE** [comment]
Anyway thanks for your help 😘
