### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Faq** [2365103939/ExtremeDumper#2]
As there are not much info about this tool.
Just wondering what is purpose of this tool as there is MegaDumper. Is this project some sort improved MegaDumper?
If yes, then what are actual improvements ExtremeDumper vs MegaDumper? Would be good such info to be in readme https://github.com/wwh1004/ExtremeDumper

**Comment by wwh1004** [comment]
support both x86 and x64
inject to any process with .net fx 2.0~4.8
inspect .net modules
much faster

and some other functions i don't mentioned above are removed currently for people almost don't need.

**Comment by wwh1004** [comment]
i will write a readme if i have time. there was a description for it in a chinese forum, so i didn't write an english readme in github. i just open source in github and people can get source.

**Comment by Faq** [comment]
ok, found it https://www.52pojie.cn/thread-712611-1-1.html

**Comment by wwh1004** [comment]
I have added some simple description.
