### ISSUE TITLE
.Net 程序，但无法检测到clr

### ISSUE THREAD

**Issue by wuyu8512** [2365103939/ExtremeDumper#6]
我这里有一个程序，确实是.Net的，反编译后能得到类型成员，但无法得到方法内具体代码
用这个软件查看后是检测不到clr的，也无法dump
请问可以发你看看吗

**Comment by wwh1004** [comment]
右键进程点击"View Modules"打开模块视图，截图发这里。你那个应该没加载clr.dll所以看不见。

**Comment by wuyu8512** [comment]
仔细一看是没检测到进程
开启DebugPrivilege后检测到了，非常感谢编写软件！
